upstream fastcgi_backend {
    server 127.0.0.1:9000;
}

server {
    listen 80 default_server;
    server_name _;
    root /var/www/html;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_pass fastcgi_backend;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $request_filename;
        fastcgi_param SCRIPT_NAME $fastcgi_script_name;
        fastcgi_read_timeout 300;
        fastcgi_param PHP_VALUE "upload_max_filesize=64M \n post_max_size=64M \n log_errors=1";
        fastcgi_param PHP_ADMIN_VALUE "error_log=/dev/stderr";
    }
}
